-- plugin dev/testing
return {
    -- {
    --     dir = "~/repos/speedtyper.nvim/",
    --     cmd = "Speedtyper",
    --     opts = {
    --         window = {
    --             -- width = 0.3,
    --         },
    --         language = "en",
    --         -- custom_text_file = "/home/nstefan002/test.txt",
    --         -- randomize = true,
    --         game_modes = {
    --             countdown = {
    --                 time = 30,
    --             },
    --             stopwatch = {
    --                 hide_time = true,
    --             },
    --             rain = {
    --                 initial_speed = 0.5,
    --                 throttle = -1,
    --                 lives = 3,
    --             },
    --         },
    --         highlights = {
    --             -- falling_word_typed = "Error",
    --         },
    --         vim_opt = {
    --             guicursor = "ver25",
    --         },
    --     },
    -- },
    -- {
    --     dir = "~/repos/mdmaker.nvim/",
    --     cmd = "MdMake",
    --     opts = {
    --         dir = "~/.config/nvim/",
    --         version_manager = { name = "bob", url = "https://github.com/MordechaiHadad/bob" },
    --         gui = { name = "Neovide", url = "https://neovide.dev/" },
    --         title = "",
    --         enable_url_check = true,
    --     },
    -- },
}
